#!/bin/sh
v="1.3"
echo "VERSION: ${v}" > oc22/VERSION.TXT
echo "VERSION: ${v}" > oc23/VERSION.TXT
rm -f *\.zip
(cd oc22;/usr/bin/zip -rD ../v2pagecache-oc22-${v}.ocmod.zip *.TXT upload/)
(cd oc23;/usr/bin/zip -rD ../v2pagecache-oc23-${v}.ocmod.zip *.TXT upload/)
